name: Tspry CI/CD

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: build
        run: |
          npm install
          npm run build

  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: test
        run: |
          npm install
          npm run test
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage
          flags: unittests # optional
          name: codecov-tspry # optional
          fail_ci_if_error: true # optional (default = false)

  # Deploy:
  #   runs-on: ubuntu-latest
  #   needs: Test
